export const getEnemy = () => {
  let enemies = [
    {
      name: "slime",
      life: 20,
      maxLife: 20,
      speed: 5,
      actionPoints: 0,
      action: "chanting",
      dmg: 5,
      spellInput: [],
      spell: "missle",
    },
    {
      name: "turtle",
      life: 30,
      maxLife: 30,
      speed: 6,
      actionPoints: 0,
      action: "chanting",
      dmg: 10,
      spellInput: [],
      spell: "missle",
    },
    {
      name: "skeleton",
      life: 40,
      maxLife: 40,
      speed: 7,
      actionPoints: 0,
      action: "chanting",
      dmg: 15,
      spellInput: [],
      spell: "missle",
    },
    {
      name: "waspoid",
      life: 50,
      maxLife: 50,
      speed: 8,
      actionPoints: 0,
      action: "chanting",
      dmg: 20,
      spellInput: [],
      spell: "missle",
    },
    {
      name: "drake",
      life: 60,
      maxLife: 60,
      speed: 9,
      actionPoints: 0,
      action: "chanting",
      dmg: 25,
      spellInput: [],
      spell: "missle",
    },
    {
      name: "eye",
      life: 40,
      maxLife: 40,
      speed: 9,
      actionPoints: 0,
      action: "chanting",
      dmg: 30,
      spellInput: [],
      spell: "missle",
    },
    {
      name: "ghoul",
      life: 90,
      maxLife: 90,
      speed: 3,
      actionPoints: 0,
      action: "chanting",
      dmg: 35,
      spellInput: [],
      spell: "missle",
    },
    {
      name: "magus",
      life: 90,
      maxLife: 90,
      speed: 9,
      actionPoints: 0,
      action: "chanting",
      dmg: 40,
      spellInput: [],
      spell: "missle",
    },
  ];
  return enemies;
};
