export const getEnemy = () => {
  let enemies = [
    {
      name: "slime",
      life: 20,
      maxLife: 20,
      speed: 5,
      actionPoints: 0,
      action: "chanting",
      dmg: 5,
    },
    {
      name: "turtle",
      life: 30,
      maxLife: 30,
      speed: 6,
      actionPoints: 0,
      action: "chanting",
      dmg: 10,
    },
    {
      name: "skeleton",
      life: 40,
      maxLife: 40,
      speed: 7,
      actionPoints: 0,
      action: "chanting",
      dmg: 15,
    },
    {
      name: "waspoid",
      life: 50,
      maxLife: 50,
      speed: 8,
      actionPoints: 0,
      action: "chanting",
      dmg: 20,
    },
    {
      name: "drake",
      life: 60,
      maxLife: 60,
      speed: 9,
      actionPoints: 0,
      action: "chanting",
      dmg: 25,
    },
    {
      name: "eye",
      life: 40,
      maxLife: 40,
      speed: 9,
      actionPoints: 0,
      action: "chanting",
      dmg: 30,
    },
    {
      name: "ghoul",
      life: 90,
      maxLife: 90,
      speed: 3,
      actionPoints: 0,
      action: "chanting",
      dmg: 35,
    },
    {
      name: "magus",
      life: 90,
      maxLife: 90,
      speed: 9,
      actionPoints: 0,
      action: "chanting",
      dmg: 40,
    },
  ];
  return enemies;
};
